apiVersion: v2
name: nightowl
description: NightOwl â€” 24/7 Operations Platform
type: application
version: 0.1.4
appVersion: "0.1.4"
maintainers:
  - name: Wisbric
    url: https://wisbric.com
keywords:
  - incident-management
  - on-call
  - alert-management
  - knowledge-base
