{{- if .Values.podDisruptionBudget.enabled -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "nightowl.fullname" . }}-api
  labels:
    {{- include "nightowl.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "nightowl.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: api
{{- end }}
